import { Trash2, X } from 'lucide-react';

import type {
  Eingabetyp,
  ModalState,
  Struktur,
  TrackerDatentyp,
} from '../types';

export function Modal({ modal, structure, name, parentId, inputType, dataType, setName, setParentId, setInputType, setDataType, onClose, onSubmit }: { modal: Exclude<ModalState, null>; structure: Struktur; name: string; parentId: string; inputType: Eingabetyp; dataType: TrackerDatentyp; setName: (value: string) => void; setParentId: (value: string) => void; setInputType: (value: Eingabetyp) => void; setDataType: (value: TrackerDatentyp) => void; onClose: () => void; onSubmit: () => void }) {
  const isTracker = modal.type === 'tracker'; const isRename = modal.mode === 'rename'; const isMove = modal.mode === 'move';
  const categories = structure.kategorien.filter((item) => item.aktiv); const areas = structure.bereiche.filter((item) => item.aktiv); const views = structure.ansichten.filter((item) => item.aktiv);
  const title = isMove ? 'Bereich verschieben' : isRename ? 'Element umbenennen' : modal.mode === 'edit' ? 'Tracker bearbeiten' : modal.type === 'kategorie' ? 'Kategorie anlegen' : modal.type === 'bereich' ? 'Bereich anlegen' : modal.type === 'ansicht' ? 'Ansicht anlegen' : 'Tracker anlegen';
  const needsParent = isMove || (!isRename && modal.type !== 'kategorie');
  const parentOptions = isMove ? categories.filter((category) => !category.bereichIds.includes(modal.id)).map((item) => ({ id: item.id, name: item.name })) : modal.type === 'bereich' ? categories.map((item) => ({ id: item.id, name: item.name })) : modal.type === 'ansicht' ? areas.map((item) => ({ id: item.id, name: item.name })) : views.map((item) => ({ id: item.id, name: item.name }));
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal__header"><div><h2 className="modal__title" id="modal-title">{title}</h2><p className="modal__description">{isMove ? 'Der Bereich bleibt erhalten und wird einer anderen Kategorie zugeordnet.' : isTracker ? 'Tracker werden zentral gespeichert und können mehreren Ansichten zugeordnet werden.' : 'Änderungen werden direkt auf diesem Gerät gespeichert.'}</p></div><button className="icon-button" type="button" onClick={onClose} aria-label="Dialog schließen"><X size={17} /></button></div><form className="modal__form" onSubmit={(event) => { event.preventDefault(); onSubmit(); }}>{!isMove ? <label className="field"><span className="field__label">Name</span><input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Name des Elements" /></label> : null}{needsParent ? <label className="field"><span className="field__label">{isMove ? 'Neue Kategorie' : modal.type === 'bereich' ? 'Kategorie' : modal.type === 'ansicht' ? 'Bereich' : 'Ansicht'}</span><select value={parentId} onChange={(event) => setParentId(event.target.value)}>{parentOptions.map((option) => <option value={option.id} key={option.id}>{option.name}</option>)}</select></label> : null}{isTracker ? <><label className="field"><span className="field__label">Datentyp</span><select value={dataType} onChange={(event) => setDataType(event.target.value as TrackerDatentyp)}><option>Messwert</option><option>Ereignis</option><option>Notiz</option></select></label><label className="field"><span className="field__label">Eingabetyp</span><select value={inputType} onChange={(event) => setInputType(event.target.value as Eingabetyp)}>{['Zahl', 'Dezimalzahl', 'Text', 'Mehrzeiliger Text', 'Ja/Nein', 'Bewertung 0 bis 10', 'Auswahlliste', 'Datum', 'Uhrzeit', 'Dauer', 'Mehrfachauswahl'].map((option) => <option key={option}>{option}</option>)}</select></label></> : null}<div className="modal__actions"><button className="button button--quiet" type="button" onClick={onClose}>Abbrechen</button><button className="button button--primary" type="submit" disabled={(!isMove && !name.trim()) || (needsParent && !parentId)}><Check size={15} />Speichern</button></div></form></section></div>;
}

export function DeleteModal({ name, onClose, onConfirm }: { name: string; onClose: () => void; onConfirm: () => void }) { return <div className="modal-backdrop" role="presentation"><section className="modal modal--confirm" role="dialog" aria-modal="true" aria-labelledby="delete-title"><div className="modal__header"><div><h2 className="modal__title" id="delete-title">Element löschen?</h2><p className="modal__description">„{name}“ wird aus der lokalen Struktur entfernt. Die Daten des globalen Trackers bleiben erhalten, bis der Tracker selbst gelöscht wird.</p></div><button className="icon-button" type="button" onClick={onClose} aria-label="Dialog schließen"><X size={17} /></button></div><div className="modal__actions"><button className="button button--quiet" type="button" onClick={onClose}>Abbrechen</button><button className="button button--danger" type="button" onClick={onConfirm}><Trash2 size={15} />Löschen</button></div></section></div>; }

const chatDays = (structure: Struktur): Tagesdatensatz[] => {
  const ids = Object.fromEntries(getAllTrackers(structure).map((item) => [item.name, item.id]));
  return [
    { id: 'chat-startdaten-2026-07-20', datum: '2026-07-20', messwerte: { [ids['Schlafdauer']]: 5.9, [ids['Beginn der Bettzeit']]: '23:00', [ids['Ende der Bettzeit']]: '05:00', [ids['subjektive Schlafqualität']]: 7, [ids['Energie']]: 8, [ids['Konzentration']]: 7, [ids['Stimmung']]: 7, [ids['Fahrradkilometer']]: 10, [ids['Anteil Hauptgericht']]: 1, [ids['geschätzte zusätzliche Kohlenhydrate']]: 110 }, ereignisse: { [ids['Mirtazapin']]: true, [ids['Training durchgeführt']]: false, [ids['Trainingsstufe']]: 'keine', [ids['Bulletproof Coffee']]: 2, [ids['Wildbeer-Protein-Smoothie']]: true, [ids['Hauptgericht']]: 'Gericht B', [ids['zusätzliche Lebensmittel']]: 'Etwa 500 g süßes Gebäck.' }, notizen: 'Nach Gericht B erneut hungrig. Tagsüber war der Hunger gut kontrollierbar.', erstelltAm: '2026-07-20T12:00:00.000Z', geaendertAm: '2026-07-20T12:00:00.000Z' },
    { id: 'chat-startdaten-2026-07-22', datum: '2026-07-22', messwerte: { [ids['Schlafdauer']]: 6.7, [ids['Beginn der Bettzeit']]: '22:00', [ids['Ende der Bettzeit']]: '05:00', [ids['subjektive Schlafqualität']]: 8, [ids['Energie']]: 8, [ids['Konzentration']]: 8, [ids['Stimmung']]: 9, [ids['Fahrradkilometer']]: 10, [ids['Anteil Hauptgericht']]: 0.75 }, ereignisse: { [ids['Mirtazapin']]: false, [ids['Training durchgeführt']]: true, [ids['Trainingsart']]: 'Bauchtraining', [ids['Trainingsstufe']]: 'Stufe 2', [ids['Bulletproof Coffee']]: 2, [ids['Hauptgericht']]: 'Gericht C' }, notizen: 'Zweiter aufeinanderfolgender Tag ohne Mirtazapin. Trotz 6,7 Stunden Schlaf waren Energie, Konzentration und Stimmung gut.', erstelltAm: '2026-07-22T12:00:00.000Z', geaendertAm: '2026-07-22T12:00:00.000Z' },
  ];
};
